name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install required tools
        run: sudo apt-get update && sudo apt-get install -y bsdmainutils

      - name: Setup ROS 2 workspace
        shell: bash
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install -i --from-path src --rosdistro humble -y

      - name: Build ROS 2 workspace
        shell: bash
        run: |
          cd /root/ros2_ws
          colcon build
          source install/setup.bash

      - name: Build and test with dependencies
        shell: bash
        run: |
          cd /root/ros2_ws
          # 環境セットアップ
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          # テスト実行
          bash -xv ./src/mypkg/test/test.bash /root
  
