name: ROS 2 CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup workspace
        run: |
          mkdir -p /root/ros2_ws/src
          rsync -av ./ /root/ros2_ws/src/

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-common-extensions python3-rosdep
          sudo rm -f /etc/ros/rosdep/sources.list.d/20-default.list || true
          sudo rosdep init || true
          rosdep update

      - name: Resolve dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          rosdep install --from-paths /root/ros2_ws/src --ignore-src -r -y

      - name: Build and test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          cd /root/ros2_ws
          colcon build
          colcon test
          colcon test-result --all

