name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions rsync

      - name: Setup ROS environment
        run: |
          echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc
          source ~/.bashrc

      - name: Prepare workspace
        run: |
          mkdir -p /root/ros2_ws/src
          rsync -a $GITHUB_WORKSPACE/ /root/ros2_ws/src/
          cd /root/ros2_ws
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build and test
        run: |
          source /opt/ros/foxy/setup.bash
          cd /root/ros2_ws
          colcon build
          source install/setup.bash

      - name: Run Weather Publisher
        run: |
          source /opt/ros/foxy/setup.bash
          source /root/ros2_ws/install/setup.bash
          ros2 run mypkg weather_publisher &
          sleep 5

      - name: Run Weather Analyzer
        run: |
          source /opt/ros/foxy/setup.bash
          source /root/ros2_ws/install/setup.bash
          ros2 run mypkg weather_analyzer &
          sleep 5

      - name: Echo Weather Data Topic
        run: |
          source /opt/ros/foxy/setup.bash
          source /root/ros2_ws/install/setup.bash
          ros2 topic echo /weather_data

