name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
      - name: Build and Test
        run: |
          source /opt/ros/foxy/setup.bash
          colcon build
          colcon test --event-handlers console_direct+

