name: CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-colcon-common-extensions python3-rosdep

      - name: Setup ROS dependencies
        run: |
          . /opt/ros/humble/setup.bash
          sudo rosdep init
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build and test
        run: |
          . /opt/ros/humble/setup.bash
          colcon build
          colcon test
          colcon test-result --all

