name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions rsync

      - name: Setup ROS environment
        run: |
          rosdep update

      - name: Prepare workspace
        run: |
          mkdir -p /root/ros2_ws/src
          rsync -a $GITHUB_WORKSPACE/ /root/ros2_ws/src/
          cd /root/ros2_ws
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build the package
        run: |
          bash -c "source /opt/ros/foxy/setup.bash && cd /root/ros2_ws && colcon build"

      - name: Run tests
        run: |
          bash -c "source /opt/ros/foxy/setup.bash && cd /root/ros2_ws && colcon test --event-handlers console_direct+"

      - name: Test the topic publish/subscribe functionality
        run: |
          bash -c "source /opt/ros/foxy/setup.bash && ros2 run mypkg weather_publisher & ros2 run mypkg weather_analyzer & ros2 topic echo /weather_data"

