name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: osrf/ros:foxy-desktop
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        shell: bash
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions rsync

      - name: Initialize rosdep
        shell: bash
        run: |
          rosdep init || true
          rosdep update

      - name: Prepare workspace
        shell: bash
        run: |
          mkdir -p /root/ros2_ws/src
          rsync -a $GITHUB_WORKSPACE/ /root/ros2_ws/src/
          cd /root/ros2_ws
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build and source
        shell: bash
        run: |
          source /opt/ros/foxy/setup.bash
          cd /root/ros2_ws
          colcon build
          source install/setup.bash

      - name: Run Weather Publisher
        shell: bash
        run: |
          source /opt/ros/foxy/setup.bash
          source /root/ros2_ws/install/setup.bash
          ros2 run mypkg weather_publisher &
          sleep 5

      - name: Run Weather Analyzer
        shell: bash
        run: |
          source /opt/ros/foxy/setup.bash
          source /root/ros2_ws/install/setup.bash
          ros2 run mypkg weather_analyzer &
          sleep 5

      - name: Wait for weather_data topic
        shell: bash
        run: |
          source /opt/ros/foxy/setup.bash
          source /root/ros2_ws/install/setup.bash
          for i in {1..10}; do
            if ros2 topic list | grep -q "/weather_data"; then
              echo "Topic /weather_data is now available."
              break
            fi
            echo "Waiting for /weather_data topic..."
            sleep 2
          done

      - name: Echo Weather Data Topic
        shell: bash
        run: |
          source /opt/ros/foxy/setup.bash
          source /root/ros2_ws/install/setup.bash
          ros2 topic echo /weather_data --once

