name: ROS 2 CI

on:
  push:
    branches:
      - main  # 'main'ブランチへのプッシュ時に実行される
  pull_request:
    branches:
      - main  # 'main'ブランチへのPR作成時に実行される

jobs:
  build:
    runs-on: ubuntu-latest  # 最新のUbuntu環境で実行

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          curl \
          gnupg2 \
          lsb-release \
          build-essential \
          cmake \
          python3-colcon-common-extensions \
          python3-pip

    - name: Install ROS 2 dependencies
      run: |
        sudo curl -sSL https://get.ros.org/ros2/foxy/setup.bash | sudo bash
        sudo apt install -y \
          ros-foxy-ros-base \
          python3-rosdep

    - name: Install dependencies using rosdep
      run: |
        sudo rosdep init
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro foxy -y

    - name: Build the workspace
      run: |
        source /opt/ros/foxy/setup.bash
        cd ~/ros2_ws
        colcon build --symlink-install

    - name: Run tests
      run: |
        source ~/ros2_ws/install/setup.bash
        colcon test
        colcon test-result --verbose

