name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y bsdmainutils python3-pip

      - name: Setup ROS 2 workspace
        shell: bash
        run: |
          rsync -av ./ /root/ros2_ws/src
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          rosdep update
          rosdep install -i --from-path src --rosdistro humble -y

      - name: Build ROS 2 workspace
        shell: bash
        run: |
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          colcon build --packages-select person_msgs --symlink-install
          colcon build --symlink-install

      - name: Verify Python environment
        shell: bash
        run: |
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          echo "PYTHONPATH: $PYTHONPATH"
          python3 -c "from person_msgs.msg import Person; print('person_msgs module is available')"
      
      - name: Debug person_msgs
        shell: bash
        run: |
          cd /root/ros2_ws
          source install/setup.bash
          echo "Installed files in person_msgs:"
          ls -R install/person_msgs


      - name: Run tests
        shell: bash
        run: |
          cd /root/ros2_ws
          source /opt/ros/humble/setup.bash
          source install/setup.bash
          bash -xv ./src/mypkg/test/test.bash /root
  
